version: "3.9"

services:
  db:
    image: mysql:8.0.34
    container_name: jobs-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobs
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      retries: 10
      start_period: 10s

  mock-external:
    build: ./mock_service
    container_name: mock-external
    ports:
      - "8081:8081"

  job-server:
    build: .
    container_name: job-server
    depends_on:
      - db
      - mock-external
    ports:
      - "8080:8080"

volumes:
  db_data:
